# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SJPromiseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SJPromiseDemo
  pod 'SJPromise', :path => '../'

  target 'SJPromiseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJPromiseDemoUITests' do
    # Pods for testing
  end

end
